#!/usr/bin/env python3
"""
Restaurant Contact Scraper Web Application
Flask backend providing single and batch scraping, Schema.org parsing,
search enrichment, Gemini AI validation, and export endpoints.
"""

import os
import csv
import json
import io
from flask import Flask, render_template, request, jsonify, Response
from scraper.core import RestaurantScraper
from scraper.ai import get_gemini_api_key

app = Flask(__name__)
scraper = RestaurantScraper(timeout=12, max_subpages=4)

# Path to the pre-scraped dataset
DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
HOUSTON_DATA_FILE = os.path.join(DATA_DIR, 'houston_restaurants_scraped.json')


@app.route('/')
def index():
    """Serve the main web application UI."""
    return render_template('index.html')


@app.route('/api/ai-status', methods=['GET'])
def ai_status():
    """Return whether Gemini AI key is present and ready in the environment."""
    key = get_gemini_api_key()
    return jsonify({
        'ai_available': bool(key),
        'model': 'gemini-2.5-flash',
        'key_preview': f"{key[:6]}...{key[-4:]}" if key else None
    })


@app.route('/api/scrape-single', methods=['POST'])
def scrape_single():
    """Scrape a single restaurant with search enrichment, Schema.org, and Gemini AI."""
    data = request.get_json() or {}
    name = data.get('name', '').strip()
    url = data.get('url', '').strip()
    location = data.get('location', 'Houston, TX').strip()
    use_ai = data.get('use_ai', True)
    custom_key = data.get('gemini_api_key', '').strip() or None

    if not name and not url:
        return jsonify({'error': 'Please provide at least a restaurant name or website link.'}), 400

    try:
        result = scraper.scrape_restaurant(
            name=name,
            url=url,
            location=location,
            use_ai=use_ai,
            custom_gemini_key=custom_key
        )
        return jsonify({'success': True, 'data': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@app.route('/api/scrape-batch', methods=['POST'])
def scrape_batch():
    """Scrape a batch of restaurants concurrently with AI and multi-source enrichment."""
    data = request.get_json() or {}
    items = data.get('items', [])
    workers = min(int(data.get('workers', 5)), 10)
    use_ai = data.get('use_ai', True)
    custom_key = data.get('gemini_api_key', '').strip() or None

    if not items:
        return jsonify({'error': 'No restaurant items provided.'}), 400

    try:
        results = scraper.scrape_batch(
            items,
            max_workers=workers,
            use_ai=use_ai,
            custom_gemini_key=custom_key
        )
        return jsonify({'success': True, 'count': len(results), 'data': results})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@app.route('/api/houston-dataset', methods=['GET'])
def get_houston_dataset():
    """Return the pre-scraped 110 Houston restaurant dataset."""
    if os.path.exists(HOUSTON_DATA_FILE):
        with open(HOUSTON_DATA_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return jsonify({'success': True, 'count': len(data), 'data': data})
    return jsonify({'error': 'Houston dataset file not found.'}), 404


@app.route('/api/export-csv', methods=['POST'])
def export_csv():
    """Generate a downloadable CSV file from submitted results."""
    data = request.get_json() or {}
    results = data.get('results', [])

    if not results:
        return jsonify({'error': 'No results to export.'}), 400

    output = io.StringIO()
    fieldnames = ['row', 'name', 'url', 'address', 'primary_phone', 'primary_email', 'phone', 'email', 'facebook', 'instagram', 'linkedin', 'sources', 'ai_confidence', 'ai_notes']
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction='ignore')
    writer.writeheader()
    writer.writerows(results)

    output.seek(0)
    return Response(
        output.getvalue(),
        mimetype="text/csv",
        headers={"Content-Disposition": "attachment;filename=scraped_restaurant_contacts.csv"}
    )


@app.route('/api/export-sheets-script', methods=['POST'])
def export_sheets_script():
    """Generate a Google Apps Script snippet to fill columns G & H."""
    data = request.get_json() or {}
    results = data.get('results', [])

    lines = [
        "/**",
        " * Auto-generated by Restaurant Contact Scraper Web App (AI Powered)",
        " * Paste this in Extensions > Apps Script in your Google Spreadsheet, then click Run.",
        " */",
        "function fillRestaurantContacts() {",
        "  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();",
        ""
    ]

    count = 0
    for idx, r in enumerate(results):
        row = r.get('row') or (idx + 6)
        phone = r.get('primary_phone') or (r.get('phone', '').split(', ')[0] if r.get('phone') else '')
        email = r.get('primary_email') or (r.get('email', '').split(', ')[0] if r.get('email') else '')
        phone = phone.replace('"', '\\"')
        email = email.replace('"', '\\"')

        if phone or email:
            if phone:
                lines.append(f'  sheet.getRange("G{row}").setValue("{phone}");')
            if email:
                lines.append(f'  sheet.getRange("H{row}").setValue("{email}");')
            count += 1

    lines.append("")
    lines.append("  SpreadsheetApp.flush();")
    lines.append(f'  Logger.log("Finished populating {count} restaurant rows!");')
    lines.append("}")

    script_content = "\n".join(lines)
    return Response(
        script_content,
        mimetype="text/javascript",
        headers={"Content-Disposition": "attachment;filename=update_google_sheet.gs"}
    )


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    print(f"[*] Starting Restaurant Contact Scraper Web App on http://127.0.0.1:{port}")
    app.run(host='0.0.0.0', port=port, debug=False)
