#!/usr/bin/env python3
"""
Restaurant Contact Scraper CLI
Extracts phone numbers, emails, and social media links from restaurant websites.
"""

import argparse
import csv
import json
import os
import sys
from scraper.core import RestaurantScraper


def load_input_file(filepath: str) -> list[dict]:
    """Load restaurant records from CSV or JSON."""
    if not os.path.exists(filepath):
        print(f"Error: Input file '{filepath}' not found.")
        sys.exit(1)

    items = []
    if filepath.endswith('.json'):
        with open(filepath, 'r', encoding='utf-8') as f:
            items = json.load(f)
    else:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            reader = csv.DictReader(f)
            for idx, row in enumerate(reader):
                name = row.get('name') or row.get('Restaurant') or row.get('Title') or f"Restaurant_{idx+1}"
                url = row.get('url') or row.get('link') or row.get('Website') or row.get('URL')
                if url:
                    item = {'name': name, 'url': url}
                    if 'row' in row:
                        item['row'] = int(row['row'])
                    items.append(item)
    return items


def save_results_csv(filepath: str, results: list[dict]):
    """Export results to CSV format."""
    if not results:
        return
    fieldnames = ['row', 'name', 'url', 'phone', 'email', 'facebook', 'instagram', 'linkedin', 'twitter']
    # Filter fieldnames based on available keys
    available_fields = [f for f in fieldnames if any(f in r for r in results)]

    with open(filepath, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=available_fields, extrasaction='ignore')
        writer.writeheader()
        writer.writerows(results)
    print(f"[OK] Saved CSV to: {filepath}")


def save_results_json(filepath: str, results: list[dict]):
    """Export results to JSON format."""
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    print(f"[OK] Saved JSON to: {filepath}")


def generate_apps_script(results: list[dict], output_file: str = "update_google_sheet.gs"):
    """Generate a Google Apps Script that automatically populates Columns G and H in Google Sheets."""
    lines = [
        "/**",
        " * Auto-generated by Restaurant Contact Scraper",
        " * Paste this into Extensions > Apps Script in Google Sheets, then click Run.",
        " */",
        "function fillRestaurantContacts() {",
        "  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();",
        ""
    ]

    count = 0
    for r in results:
        row = r.get('row')
        phone = r.get('phone', '').split(', ')[0].replace('"', '\\"') if r.get('phone') else ''
        email = r.get('email', '').split(', ')[0].replace('"', '\\"') if r.get('email') else ''

        if row and (phone or email):
            if phone:
                lines.append(f'  sheet.getRange("G{row}").setValue("{phone}");')
            if email:
                lines.append(f'  sheet.getRange("H{row}").setValue("{email}");')
            count += 1

    lines.append("")
    lines.append("  SpreadsheetApp.flush();")
    lines.append('  Logger.log("Finished populating ' + str(count) + ' restaurant rows!");')
    lines.append("}")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
    print(f"[OK] Generated Google Apps Script: {output_file} ({count} rows configured)")


def progress_callback(item: dict, done: int, total: int):
    """Real-time console progress report."""
    phone_preview = item.get('phone', '')[:25] or 'N/A'
    email_preview = item.get('email', '')[:25] or 'N/A'
    print(f"[{done:3d}/{total:3d}] {item['name'][:28]:<28} | Phone: {phone_preview:<25} | Email: {email_preview}")


def main():
    parser = argparse.ArgumentParser(
        description="Restaurant Contact Scraper: Extract phone numbers, emails, and social links.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Scrape a single restaurant website:
  python main.py --url "https://theparadisehtx.com/" --name "Paradise HTX"

  # Scrape from a custom CSV input file:
  python main.py --input restaurants.csv --workers 8 --output results.csv

  # Run on the included Houston dataset and generate Google Sheets script:
  python main.py --houston --generate-apps-script
        """
    )
    parser.add_argument('--input', '-i', help="Path to input CSV or JSON containing restaurant names and URLs")
    parser.add_argument('--url', '-u', help="Scrape a single restaurant URL")
    parser.add_argument('--name', '-n', default="Target Restaurant", help="Restaurant name for single URL mode")
    parser.add_argument('--output', '-o', default="output_contacts.csv", help="Output CSV path (default: output_contacts.csv)")
    parser.add_argument('--json', help="Optional path to also export results as JSON")
    parser.add_argument('--workers', '-w', type=int, default=5, help="Number of concurrent worker threads (default: 5)")
    parser.add_argument('--timeout', '-t', type=int, default=12, help="HTTP request timeout in seconds (default: 12)")
    parser.add_argument('--houston', action='store_true', help="Use the pre-configured Houston 110 restaurants dataset")
    parser.add_argument('--generate-apps-script', action='store_true', help="Generate a Google Apps Script snippet for 1-click Google Sheet filling")

    args = parser.parse_args()
    scraper = RestaurantScraper(timeout=args.timeout)

    # 1. Single URL Mode
    if args.url:
        print(f"[*] Scraping single site: {args.name} ({args.url})")
        res = scraper.scrape_restaurant(args.name, args.url)
        print("\n--- Results ---")
        for k, v in res.items():
            print(f"  {k.capitalize():10}: {v or 'N/A'}")
        if args.output:
            save_results_csv(args.output, [res])
        return

    # 2. Determine batch items
    input_file = args.input
    if args.houston or not input_file:
        default_data = os.path.join(os.path.dirname(__file__), 'data', 'houston_restaurants.csv')
        if os.path.exists(default_data):
            input_file = default_data
            print(f"[*] Using Houston 110 restaurant dataset: {input_file}")
        else:
            print("Error: Please provide --input <file.csv> or --url <url>")
            sys.exit(1)

    items = load_input_file(input_file)
    print(f"[*] Loaded {len(items)} restaurants to scrape with {args.workers} worker threads.\n")

    results = scraper.scrape_batch(items, max_workers=args.workers, on_progress=progress_callback)

    # Summary
    found_phone = sum(1 for r in results if r.get('phone'))
    found_email = sum(1 for r in results if r.get('email'))
    found_social = sum(1 for r in results if r.get('facebook') or r.get('instagram') or r.get('linkedin'))

    print(f"\n{'='*60}")
    print(f"SUMMARY:")
    print(f"  Total Processed: {len(results)}")
    print(f"  Phones Found:    {found_phone} ({found_phone/len(results)*100:.1f}%)")
    print(f"  Emails Found:    {found_email} ({found_email/len(results)*100:.1f}%)")
    print(f"  Socials Found:   {found_social} ({found_social/len(results)*100:.1f}%)")
    print(f"{'='*60}\n")

    # Output exports
    save_results_csv(args.output, results)
    if args.json:
        save_results_json(args.json, results)

    if args.generate_apps_script:
        generate_apps_script(results)


if __name__ == '__main__':
    main()
